spring:
  application:
    name: portal
  datasource:
    url: jdbc:postgresql://localhost:5432/portal
    username: portal
    password: portal
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: portal-applications
      auto-offset-reset: earliest

portal:
  kafka:
    topics:
      application-processing: portal.application.processing
  application-processing:
    enabled: true
    fixed-delay-ms: 10000
    batch-size: 50

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/portal
    username: portal
    password: portal
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

portal:
  kafka:
    topics:
      application-processing: portal.application.processing
  application-processing:
    enabled: true
    fixed-delay-ms: 10000
    batch-size: 50

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: portal-applications-test

portal:
  kafka:
    topics:
      application-processing: portal.application.processing.test
  application-processing:
    enabled: false
